---

  # Ensure Service User account Exists
  - name: Ensure SickBeard service user exists
    user: name={{ sickbeard_user_name }}
          createhome=yes
          state=present

  # Check/Install Dependencies for Sickbeard
  - name: Ensure SickBeard dependencies are installed
    apt: name={{ item }} state=present
    with_items:
      - git
      - python
      - python-cheetah
  
  # Create Sickbeard Program Directory 
  - name: Ensure SickBeard program directory exists
    file: dest={{ sickbeard_binary_path }}
          owner={{ sickbeard_user_name }}
          group={{ sickbeard_group_name }}
          recurse=yes state=directory

  # Create Sickbeard Data Directory
  - name: Ensure SickBeard config directory exists
    file: dest={{ sickbeard_data_path }}
          owner={{ sickbeard_user_name }}
          group={{ sickbeard_group_name }}
          recurse=yes state=directory

  # Clone Sickbeard Source from Github
  - name: Fetch SickBeard from GitHub
    git: repo=https://github.com/midgetspy/Sick-Beard
         dest={{ sickbeard_binary_path }}
         update=no

  # Ensure Permissions are correct
  - name: Ensure SickBeard source is owned by service user
    file: dest={{ sickbeard_binary_path }}
          owner={{ sickbeard_user_name }}
          group={{ sickbeard_group_name }}
          recurse=yes state=directory

  # Deploy Sickbeard Default file for init.d
  - name: Deploy SickBeard Default file for init
    template: dest=/etc/default/sickbeard
              src=sickbeard.default.j2
              owner=root group=root mode=755

  # Deploy Init.d File for sickbeard  
  - name: Deploy SickBeard init.d script
    template: dest=/etc/init.d/sickbeard
              src=sickbeard.init.d.j2
              owner=root group=root mode=644

  # Ensure Sickbeard service is enabled/running
  - name: Ensure SickBeard service is running and enabled on boot
    service: name=sickbeard state=started enabled=yes
