---

- name: restart sickbeard
  service: name=sickbeard state=restarted

- name: start sickbeard
  service: name=sickbeard state=started

- name: stop sickbeard
  service: name=sickbeard state=stopped
